# Site
repository: IlariaSpada/home
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ilaria Spada
title: Assistente Sociale Specialista
email: ilaria.spada96@gmail.com
phone: +39 3343435517
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  IlariaSpada
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: ilaria-spada-3106a7242
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Chi sono
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  TODO

content:
  # - title: Progetti # Title for the section
  #  layout: list # Type of content section (list/text)
    
  #  content:
  #    - layout: left # top-middle, right
  #      title: Super awesome project
  #      link: github.com/sproogen
  #      link_text: Project Website
  #      additional_links:
  #        - title:  sproogen/modern-resume-theme
  #          icon: fab fa-github
  #          url: github.com/sproogen/modern-resume-theme
  #      quote: >
  #        Short overview of the project
  #      description: | # this will include new lines to allow paragraphs
  #        Description about the work on/with the project


  - title: Esperienze Lavorative
    layout: list # Type of content section (list/text)
    
    content:
      - layout: left
        title: Commessa di negozio di abbigliamento
        sub_title: Zuiki
        caption: 2022
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Gestione della cassa e dei pagamenti
            - Allestimento e sistemazione della merce
            - Pulizia e riordino del negozio
            - Accoglienza e supporto ai clienti
      
      - layout: left
        title: Tirocinio presso COOT
        sub_title: San Filippo Neri
        caption: maggio 2021 - agosto 2021
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Prevenire e affrontare disagi e problemi psico-socio-assistenziali connessi alla malattia, al ricovero e alla riabilitazione.
            Azione di ascolto, colloqui, di rilevazione dei bisogni e delle necessità relazionali, emotive e socio assistenziali.
            Interventi per prevenire situazioni di disagio sociale, sostegno psico sociale.
            Consulenze nei reparti per valutare le necessità socio assistenziali del paziente ed attivare percorsi di integrazione ospedale-territorio, organizzando anche attività post dimissione.
            
            - segnalazione dei casi fragili ai servizi territoriali
            - ricoveri
            - ospitalità RSA
            - favorire dimissioni protette del paziente e attivarsi per il suo inserimento nel territorio di appartenenza

      - layout: left
        title: Tirocinio presso TSMREE
        caption: 2018
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Fenomeni connessi alla disabilità, all'emarginazione del disagio socio ambientale e prevenire l'insorgenza di fattori che possono compromettere lo sviluppo della persona in campo cognitivo o relazionale, assicurando una presa in carico globale.
            
            - Progetti personalizzati per l'attivazione di percorsi che portano all'integrazione e all' autonomia degli utenti.
            - GLHO (Gruppo di Lavoro Operativo per l'Handicap) per formulare un piano educativo individualizzato (PEI)
            - Vineland Adaptive Behavior Scales, intervista rivolta ai genitori per valutare l'autonomia personale e la responsabilità sociale delle persone misurando livelli di sviluppo del comportamento adattivo nella comunicazione, nelle abilità quotidiane, nella socializzazione e nelle abilità motorie.
            - Colloqui presso Tribunale dei minori
            - Visite domiciliari
            - SISMIF (Servizio per l'Integrazione e Sostegno a Minori In Famiglia) erogato dal Municipio per sostenere minori e famiglie.
            - SAISH (Servizio per l'Autonomia e l'Integrazione sociale dei minori p con l'Handicap) ha lo scopo di migliorare l'autonomia e le relazioni all'interno della famiglia
      
      - layout: left
        title: Tirocinio presso CSM
        caption: giugno 2017 - agosto 2017
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Tutelare i diritti delle persone con disagio psichico o disturbo mentale. Accoglienza e valutazione diagnostica, percorsi di cura individualizzati mediante trattamenti psicoterapeutici, inserimenti ihn tirocini di lavoro, soggiorni estivi riabilitativi, lavoro di rete e orientamenti per il paziente e i suoi familiari circa l'utilizzo delle risorse sociali e socio-sanitarie extra ospedaliere

      - layout: left
        title: Baby Sitter
        caption: agosto 2019 - dicembre 2021
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Per l'intera settimana ho curato l'attività di tre gemelli di 2 anni in assenza dei genitori. Ho aiutato loro dalla colazione alla preparazione del pranzo e della cena.
            Inoltre:
            - ho inventato giochi e attività creative per mantenere i bambini impegnati
            - ho provveduto a farli dormire negli orari stabiliti
            - li ho curati nella pulizia personale, dal cambio del pannolino al bagnetto

      - layout: left
        title: Baby Sitter
        caption: 2019
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Ho aiutato una nonna a genstire 4 bambini dai 2 ai 6 anni in tutte le loro necessità, stando con loro dall'ora di pranzo all'ora di cena.

      - layout: left
        title: Baby Sitter
        caption: luglio 2019 - settembre 2019
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Ho sostituito per un mese una ragazza nella gestione di due gemelle di 5 mesi, aiutando la mamma a preparare le pappe, fare il bagnetto, ad intrattenerle e farle addormentare.


  - title: Formazione # Title for the section
    layout: list # Type of content section (list/text)
    
    content:
      - layout: left
        title: Laurea Magistrale in Progettazione, Gestione e Valutazione dei Servizi Sociali
        sub_title: Università La Sapienza
        caption: 110/110
        caption: 2019 - 2022

      - layout: left
        title: Webinar di criminologia - Cold Case
        #sub_title: Università La Sapienza
        caption: maggio 2021

      - layout: left
        title: Laurea triennale in Scienze e Tecniche del Servizio Sociale
        sub_title: Università La Sapienza
        caption: 2015 - 2019

      - layout: left
        title: Corso di Alta Formazione in Scienze Forensi, Criminologia investigativa, Sopralluogo Tecnico sulla Scena Del Crimine e Criminal Profiling
        #sub_title: Università La Sapienza
        caption: maggio 2018 - 2019

      - layout: left
        title: Diploma Scientifico
        sub_title: Liceo Scientifico L.A. Seneca
        caption: 2009 - 2015


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
